In [1]:
import numpy as np

class EpsilonGreedyAgent:

    def __init__(self, num_actions, epsilon=0.1):
        self.num_actions = num_actions
        self.epsilon = epsilon
        self.action_values = np.zeros(num_actions)
        self.action_counts = np.zeros(num_actions)
    # Randomly choose an action for exploration
    # Choose the greedy action for exploitation
    def select_action(self):
        # Your code here

        return action
    # Update action—value estimate using incremental update rule

    def update_value(self, action, reward):
    # your code here

class MultiArmedBandit:
    def __init__(self, num_arms):
        self.num_arms = num_arms
        self.true_action_values = np.random.normal(0, 1, num_arms)
    # Reward is sampled from a normal distribution with mean true action value and unit variance
    def get_reward(setf, action):
    # your code here
num_arms = 10
num_steps = 1000
agent = EpsilonGreedyAgent(num_arms)

bandit = MultiArmedBandit(num_arms)
total_rewards = 0

for step in range(num_steps):
    action = agent.select_action()
    reward = bandit.get_reward(action)
    agent.update_value(action, reward)
    total_rewards += reward
print ("Total rewards obtained:" , total_rewards)
print ("Estimated action values:", agent.action_values)

IndentationError: expected an indented block after class definition on line 3 (1087732873.py, line 4)

In [2]:
import numpy as np

class EpsilonGreedyAgent:
    def __init__(self, num_actions, epsilon=0.1):
        self.num_actions = num_actions
        self.epsilon = epsilon
        self.action_values = np.zeros(num_actions)
        self.action_counts = np.zeros(num_actions)

    def select_action(self):
        if np.random.rand() < self.epsilon:
            # Explore: choose a random action
            action = np.random.randint(self.num_actions)
        else:
            # Exploit: choose the action with the highest estimated value
            action = np.argmax(self.action_values)
        return action

    def update_value(self, action, reward):
        # Incremental update of action value using the sample average method
        self.action_counts[action] += 1
        alpha = 1 / self.action_counts[action]
        self.action_values[action] += alpha * (reward - self.action_values[action])

class MultiArmedBandit:
    def __init__(self, num_arms):
        self.num_arms = num_arms
        self.true_action_values = np.random.normal(0, 1, num_arms)

    def get_reward(self, action):
        # Reward is sampled from a normal distribution with mean true action value and unit variance
        reward = np.random.normal(self.true_action_values[action], 1)
        return reward

# Parameters
num_arms = 10
num_steps = 1000

# Instantiate agent and bandit
agent = EpsilonGreedyAgent(num_arms)
bandit = MultiArmedBandit(num_arms)

# Simulation
total_rewards = 0

for step in range(num_steps):
    action = agent.select_action()
    reward = bandit.get_reward(action)
    agent.update_value(action, reward)
    total_rewards += reward

print("Total rewards obtained:", total_rewards)
print("Estimated action values:", agent.action_values)

Total rewards obtained: 440.05801874413316
Estimated action values: [-0.54186874  0.14697717 -0.43735594 -1.18234497 -0.83651343  0.51686067
  0.55289309 -0.95752384 -0.05279096 -0.66404973]


In [3]:
import numpy as np

class GridWorld:

    def __init__(self):
        self.grid_size = (3, 3)
        # There are Up, Down, Left, Right actions
        self.num_actions = 4  # Define number of actions
        self.rewards = np.array([
            [0, 0, 0],
            [0, 0, 0],
            [0, 1, 0]  # Reward of +1 in the bottom-right cell
        ])

    def get_reward(self, state):
        # Extract the row and column from the state tuple
        row, col = state
        # Return the reward associated with the given state
        return self.rewards[row, col]

class ValueFunction:

    # Create values array with same size as grid and initialize all elements to zero
    def __init__(self, grid_size):
        self.values = np.zeros(grid_size)

    # Update value at specified state with new_value
    def update_value(self, state, new_value):
        row, col = state
        self.values[row, col] = new_value

    # Get value at specified state
    def get_value(self, state):
        row, col = state
        return self.values[row, col]
    
grid_world = GridWorld()
value_function = ValueFunction(grid_world.grid_size)

# Initialize the value function with the rewards associated with each cell
for i in range(grid_world.grid_size[0]):
    for j in range(grid_world.grid_size[1]):
        value_function.update_value((i, j), grid_world.get_reward((i, j)))

# Print the initial value function to see the value estimates for each state
print("Initial value function:")
print(value_function.values)

Initial value function:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 0.]]
